Update Gradle cache version to jars-8
android/compose-samples pull request #146
Opened 2020-09-04 14:08 UTC by starsep

I have noticed that I do not have directory `~/.gradle/caches/jars-3` locally.
On my computer `ls ~/.gradle/caches/ | grep jars` returns jars-8 only.

Reference: https://github.com/gradle/gradle/blob/1e3ce9cf4394e3e0e290ef4a647ffb5e0d1343dc/subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultClasspathTransformerCacheFactory.java#L46

All samples use Gradle 6.6 at the moment:

`grep -R distributionUrl`

> Owl/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip
Jetsnack/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip
JetNews/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip
Jetchat/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip
Jetsurvey/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip
Crane/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip
Rally/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip
Jetcaster/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip

2020-09-08 09:16 UTC, JoseAlcerreca commented
Good c̶a̶c̶h̶e̶ catch! I'm going to let Chris merge this one.

2020-09-14 10:12 UTC, chrisbanes requested changes
Let's just use wildcards instead. @starsep are you happy to copy these changes to the other samples? 

No worries if not, I'll do it.

2020-09-14 10:12 UTC, chrisbanes commented on .github/workflows/Crane.yaml
>              ~/.gradle/caches/modules-2
```suggestion
            ~/.gradle/caches/modules-*
```

2020-09-14 10:12 UTC, chrisbanes commented on .github/workflows/Crane.yaml
> +            ~/.gradle/caches/jars-8
```suggestion
            ~/.gradle/caches/jars-*
```

2020-09-14 10:12 UTC, chrisbanes commented on .github/workflows/Crane.yaml
>              ~/.gradle/caches/build-cache-1
```suggestion
            ~/.gradle/caches/build-cache-*
```

2020-09-16 07:46 UTC, chrisbanes approved these changes

2020-09-16 08:07 UTC, JoseAlcerreca approved these changes

2020-09-16 08:08 UTC, merged