[Jetsurvey] Updating to alpha11 snapshot
android/compose-samples pull request #365
Opened 2021-01-29 10:32 UTC by florina-muntenescu

2021-01-29 12:40 UTC, JolandaVerhoef approved these changes

2021-01-29 14:02 UTC, JoseAlcerreca requested changes

2021-01-29 14:02 UTC, JoseAlcerreca commented on Jetsurvey/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.8-bin.zip
```suggestion
distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.1-bin.zip
```

2021-02-01 08:41 UTC, JoseAlcerreca approved these changes

2021-02-01 08:41 UTC, merged