[Jetsurvey] Update to alpha12 snapshot
android/compose-samples pull request #384
Opened 2021-02-10 17:52 UTC by florina-muntenescu

2021-02-10 17:54 UTC, chrisbanes approved these changes

2021-02-10 18:36 UTC, yrezgui requested changes

2021-02-10 18:36 UTC, yrezgui commented on Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyScreen.kt
> +@Suppress("DEPRECATION") // ConstraintLayout
Is the new constraintlayout artifact not working for you? In case, put a note that this is temporary

2021-02-11 08:50 UTC, chrisbanes commented
Let's just commit this for now. We'll fix the ConstraintLayout stuff when we move to alpha12

2021-02-11 08:55 UTC, merged