[Jetnews] Add Previews
android/compose-samples pull request #549
Opened 2021-05-27 12:12 UTC by JolandaVerhoef

2021-05-27 13:45 UTC, nickbutcher approved these changes
One question about API level preview, otherwise LGTM.

2021-05-31 06:08 UTC, JolandaVerhoef commented
For me, it made sense to include the minSdkVersion vs the targetSdkVersion. They shouldn't differ, but if you forget to use Compat classes, they might. I don't have a strong feeling about this though. Would like to get @yrezgui 2 cents on this!

2021-06-01 09:52 UTC, yrezgui requested changes
I would remove `@Preview("api 21", "round", apiLevel = 21)` as we don't have an actual need in this sample as we don't rely on changing APIs within our previews. Better to drop them

2021-06-01 09:52 UTC, yrezgui commented on Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Button.kt
> +@Preview("api 21", "round", apiLevel = 21)
I think we don't have an actual need in this sample as we don't rely on changing APIs within our previews. Better to drop it

2021-06-03 06:46 UTC, JolandaVerhoef commented
@yrezgui I removed the API level previews. Let me know if this is better!

2021-06-03 15:37 UTC, yrezgui approved these changes

2021-06-04 07:02 UTC, merged