Update R8 to avoid minified crash with navigation-compose
android/compose-samples pull request #695
Opened 2021-11-03 18:32 UTC by alexvanyo

As reported in #692 , using version `2.4.0-alpha09` or `2.4.0-alpha10` of `navigation-compose` with a minified build will result in a crash upon startup.

I created an upstream issue [here](https://issuetracker.google.com/issues/204910734) on the navigation side, but it looks like an R8 issue since updating to a newer version than default resolves the issue.

This PR adds that workaround, updating R8 for the 3 affected projects: `JetNews`, `Jetsnack`, and `Owl` (`Jetcaster` uses `navigation-compose`, but doesn't minify the release build). If `navigation-compose` changes its implementation to avoid this bug, or the default version of R8 fixes the issue, we can revert this commit.

This fixes #692

2021-11-11 16:59 UTC, JoseAlcerreca commented
Isn't this fixed in 2.4.0 beta?

2021-11-11 18:17 UTC, alexvanyo commented
Just checked, and yep, updating to `2.4.0-beta02` seems to fix this issue (`2.4.0-beta01` still crashes)

I'll update all of the samples to the latest navigation version instead.

2021-11-12 15:11 UTC, JoseAlcerreca commented
I believe they were updated already!

2021-11-12 15:27 UTC, JoseAlcerreca commented
Correction: they weren't, and accompanist is using beta01. Is it urgent or can it wait for the next 1.1 release?

2021-11-12 15:35 UTC, JoseAlcerreca requested changes
Abandon and update to nav beta02 or wait for next release

2022-05-10 20:32 UTC, closed without merging